# 配置生成地址 https://get-images.kubesphere.io/
# 创建时间 2025-12-17
apiVersion: kubekey.kubesphere.io/v1
kind: Config
spec:
  cni:
    calico_version: v3.28.2
    cilium_version: 1.15.4
    hybridnet_version: 0.6.8
    kubeovn_version: 1.13.0
    multus:
      image:
        tag: v4.3.0
  cri:
    container_manager: docker
    containerd_version: v1.7.6
    crictl_version: v1.33.0
    cridockerd_version: v0.3.1
    docker_version: 24.0.7
    runc_version: v1.1.7
    sandbox_image:
      tag: "3.9"
  dns:
    dns_cache_image:
      tag: 1.24.0
    dns_image:
      tag: v1.12.1
  etcd:
    etcd_version: v3.5.11
  download:
    arch:
      - amd64
  image_registry:
    docker_registry_version: 2.8.3
    dockercompose_version: v2.20.3
    harbor_version: v2.10.1
    keepalived_version: 2.0.20
    type: harbor
  kubernetes:
    helm_version: v3.18.5
    kube_version: v1.33.4
  storage_class:
    local:
      linux_utils_image:
        tag: 4.2.0
      provisioner_image:
        tag: 4.2.0
    nfs_provisioner_version: 4.3.0
  # 镜像仓库拉取速率限制
  cri:
    registry:
      auths:
        # 拉取镜像时需访问的镜像仓库，如 docker.io
        - repo: REGISTRY
          # 如 docker.io 的登录账户
          username: USERNAME
          # 如 docker.io 的登录密码
          password: PASSWORD
  image_manifests:
  # kubernetes-v1.33.4
  - docker.io/calico/apiserver:v3.28.2
  - docker.io/calico/cni:v3.28.2
  - docker.io/calico/csi:v3.28.2
  - docker.io/calico/kube-controllers:v3.28.2
  - docker.io/calico/node-driver-registrar:v3.28.2
  - docker.io/calico/node:v3.28.2
  - docker.io/calico/pod2daemon-flexvol:v3.28.2
  - docker.io/kubesphere/k8s-dns-node-cache:1.24.0
  - docker.io/openebs/provisioner-localpv:4.2.0
  - docker.io/openebs/linux-utils:4.2.0
  - docker.io/kubesphere/coredns:v1.12.1
  - docker.io/kubesphere/kube-apiserver:v1.33.4
  - docker.io/kubesphere/kube-controller-manager:v1.33.4
  - docker.io/kubesphere/kube-proxy:v1.33.4
  - docker.io/kubesphere/kube-scheduler:v1.33.4
  - docker.io/kubesphere/pause:3.9
  - quay.io/tigera/operator:v1.34.5
  - docker.io/calico/ctl:v3.28.2
  - docker.io/calico/typha:v3.28.2
  - docker.io/library/haproxy:2.9.6-alpine
  # ks-core
  - registry.cn-beijing.aliyuncs.com/kse/ks-apiserver:v4.2.0-20251118
  - registry.cn-beijing.aliyuncs.com/kse/ks-console:v4.2.0-20251118
  - registry.cn-beijing.aliyuncs.com/kse/ks-controller-manager:v4.2.0-20251118
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.33.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/redis:7.2.4-alpine
  - registry.cn-beijing.aliyuncs.com/kubesphereio/redis:7.2.8-alpine
  - registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:3.0.8-alpine
  - registry.cn-beijing.aliyuncs.com/kse/extensions-museum:v11.1.2
  - registry.cn-beijing.aliyuncs.com/kse/ks-console-embed:v4.2.0-20251118
  - registry.cn-beijing.aliyuncs.com/kse/ks-posthog:v2.0.0
